name: Prepare nixpkgs
description: Prepare nixpkgs.txt input
inputs:
  packages:
    required: false
  packages_url:
    required: false

runs:
  using: composite
  steps:
    - name: Restore nixpkgs cache
      uses: actions/cache@v4
      with:
        path: nixpkgs.txt
        key: |
          nixpkgs-${{
            hashFiles('nixpkgs.txt')
          }}

    - name: Override nixpkgs.txt
      shell: bash
      run: |
        if [ -n "${{ inputs.packages_url }}" ]; then
          curl \
            -fsSL \
            "${{ inputs.packages_url }}" \
            > nixpkgs.txt
      
        elif [ -n "${{ inputs.packages }}" ]; then
          printf "%s\n" \
            "${{ inputs.packages }}" \
            > nixpkgs.txt

        elif [ ! -f nixpkgs.txt ]; then
          touch nixpkgs.txt
        fi
